### PR TITLE
[build/deps] Add the "libasan" package to the Fedora dependencies

### PR DESCRIPTION
**Pull request by akinomyoga**
Without this package, `ninja` fails.

### CODE REVIEW

**Comment by akinomyoga** [comment]
Hmm, this might also be related to the `root` files.

**Comment by andychu** [comment]
Great thanks!

**Comment by akinomyoga** [comment]
Thanks. I've modified the codes based on the `master` branch, but should I create PRs on top of `soil-straging`?

**Comment by andychu** [comment]
Yes I merge to `soil-staging`, and  then the CI merges to `master` after tests pass

It doesn't matter too much since I just change it for all contributors

**Comment by akinomyoga** [comment]
Thanks

**Pull request merged**
