### PR TITLE
Support shopt -s dotglob

### PR DESCRIPTION
**Pull request by leungbk**
Related to #610.

The Python build seems okay, but I could use some help getting the ninja build to pass; my attempt at defining GLOB_PERIOD doesn't seem to work.

```
In file included from /home/brian/oils/cpp/preamble.h:6:
_gen/bin/oils_for_unix.mycpp.cc: In member function ‘int glob_::Globber::_Glob(BigStr*, List<BigStr*>*)’:
_gen/bin/oils_for_unix.mycpp.cc:41233:22: error: expected unqualified-id before ‘(’ token
41233 |       flags |= libc::GLOB_PERIOD;
      |                      ^~~~~~~~~~~
```

### CODE REVIEW

**Comment by leungbk** [comment]
OK, I managed to resolve my problem from before: `mycpp/TEST.sh test-translator` now passes on my machine.

But I cannot tell from the GitHub interface where specifically to look to investigate the failing jobs; clicking on any single job takes me to a `publish-html` step that doesn't appear to expose anything helpful.

**Comment by andychu** [comment]
Cool, I will look at this!

Oh there is a URL hidden in the logs.

https://github.com/oils-for-unix/oils/actions/runs/12284550355/job/34280567011?pr=2194

I switched from SSH to HTTP copying, and it introduced a lot of spew, which has hidden it

I can fix that

----

In the mean time I go to 

https://op.oilshell.org/uuu/github-jobs/


which is linked on https://www.oilshell.org/    and then  look for the CI results


---

Thanks for the help!

**Comment by andychu** [comment]
Oh actually you can see a few more failures here

https://op.oilshell.org/uuu/github-jobs/8712/

https://op.oilshell.org/uuu/github-jobs/8712/dev-setup-debian.wwz/_tmp/soil/logs/py-all-and-ninja.txt

```
.......
======================================================================
ERROR: testGlob (__main__.LibcTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyext/libc_test.py", line 177, in testGlob
    print(libc.glob('\\'))
RuntimeError: unknown problem

----------------------------------------------------------------------
Ran 12 tests in 0.001s

FAILED (errors=1)
```



I am not sure what happened, I guess the default behavior changed somehow?

**Comment by andychu** [comment]
Wow this looks great, thank you!  Thanks for tracking down all the Python and C++ stuff

I think it can be OK to just pass `0` everywhere for the glob() flags ...  I don't think we have any optional args in Python right now.

---

If we don't support globskipdots, then maybe we can tweak the test so it doesn't pass?  I guess we are missing test coverage?

**Comment by leungbk** [comment]
OK, I have updated the globstar test to make sure it continues to fail.

I also corrected my comment in `glob_.py`: filtering out only `.` and `..` in the manner that I did does not always match the behavior of `shopt -s globskipdots`. I tried to look at how `bash` implemented it but couldn't quite follow all the casework.

**Comment by andychu** [comment]
Great, thank you!

Now I remember I didn't start a Zulip thread about how to implement `globstar`!  I was wondering how it behaves, and the tests really helped, particularly knowing that it's different in bash and zsh

**Pull request merged**
